apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: forgit
  name: forgit
spec:
  containers:
  - image: nginx
    name: forgit
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
